### ISSUE TITLE
Blocking echo messages on startup result in blank screen

### ISSUE THREAD

**Issue by ilyagr** [macvim-dev/macvim#1573]
### Steps to reproduce

With the latest prerelease, I run the following command (from a diff tool config, sorry for extraneous quotes):

```bash
"gvim" "-f" "-d" "-u" "/dev/null" mkdocs-offline.yml mkdocs.yml "-c" "echohl WarningMsg" "-c" "echomsg \"Warning: using plain `vimdiff` as a diff editor is not recommended. See https://github.com/jj-vcs/jj/wiki/Vim for alternatives.\"" "-c" "echohl None"
```

(It doesn't matter which two files you'd be comparing, or if they even exist)

This results in a confusing blank screen instead of the expected message:

<img width="514" alt="Image" src="https://github.com/user-attachments/assets/0bfb406e-0bec-4eaf-91b8-78c886abcf9a" />

After pressing Enter, everything works.

<img width="507" alt="Image" src="https://github.com/user-attachments/assets/9ff90836-fe1a-47a6-8971-8d10c70071d4" />

### Expected behaviour

In plain vim, I get:

```
"mkdocs-offline.yml" 19 lines, 724 bytes
"mkdocs.yml" 154 lines, 4992 bytes
Warning: using plain `vimdiff` as a diff editor is not recommended. See https://github.com/jj-vcs/jj/wiki/Vim for alter
natives.
Press ENTER or type command to continue
```

Then, vim loads after I press ENTER.

### Version of Vim and architecture

1-1251

### Environment

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Mar 28 2025 09:26:05)
macOS version - arm64
Included patches: 1-1251
Compiled by GitHub Actions

### How MacVim was installed

Downloaded from GitHub

### Logs and stack traces

```shell

```

### Issue has been tested with given configuration

- [ ] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [x] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
Let me take a look, but I think this is a bad interaction with the "Press Enter" mode in Vim and some recent resize changes in MacVim. Basically Vim's "Press Enter" mode is quite fragile in that if you resize the window, it will clear all the rendering instead of redrawing itself. This issue occurs when Vim is used in a terminal as well but MacVim may have triggered a resize event which caused this to happen.

Have you noticed this issue before (e.g. in r181) the current pre-release build (r181.1)? It would be nice to know when you have noticed that.

But as you noticed it's mostly a rendering / redraw issue in Vim and pressing enter will indeed fix the issue.

**Comment by ilyagr** [comment]
As of now, I haven't tried any other versions.

**Comment by ilyagr** [comment]
I tried using `:echowin` instead of `:echomsg`, but that didn't work inside MacVim at all. I was going to ask if I should use it instead (e.g. if it has been around for long enough), but I guess not.

It might be the same issue with resizing, since `:echowin` inside MacVim works but is cut off a bit.

**Comment by ychin** [comment]
`echowin` works. As you said it works if you type it manually. Either way it's not really the expected way to show an error message at launch so it's not going to be a good option regardless.

Also, running your command seems to trigger some serious warning. Did you actually look at the terminal output and look at what it's saying? You can wrapping "vimdiff" as \`vimdiff\` and that's going to run vimdiff in the background and make everything unhappy.

If I clean up the messages up it seems to output fine.

**Comment by ychin** [comment]
I think the issue here is multi-fold. You are using `-u /dev/null` which is equivalent to `-u NONE` which enables scroll bars which causes a resize. You are printing a message concurrently which causes a "Press Enter" prompt to show up, which gets resized and clipped.

There are multiple things you could do here:

1. Don't use `-u NONE`. At least use `-u DEFAULTS` which has better behavior on start when using diff mode (just try both without your message commands and you will see what I mean).
2. You could use `echowin` after doing (1) above.
3. You could use `:echomsg` like before but set a timer of 0 seconds using `timer_start` so that the new message doesn't literally get called immediately and interfere with Vim's own output of the file being edited and resize.
4. Play around with `messageopt` to avoid hit-enter. That said this may have the issue of stomping user defaults.

I do want to fix Vim's Press Enter prompt to be more safe to terminal resizing but I think there are other things you could do in the meantime.

Btw, seems like the issue here is that jj defaults to vimdiff, but then you want it to warn when vimdiff is used as-is? That seems like a bad default to me, as defaults should work instead of throwing up an annoying error message. If vimdiff doesn't work at all, it should just not be allowed to launch with jj explaining why. If it works, then having this error message *every time* a user wants to use it is going to get old real fast. This "kind of works but I'll annoy the hell out of you" seems like half measures to me. I don't use it though so it's up to you.

**Comment by ilyagr** [comment]
>  You are using -u /dev/null which is equivalent to -u NONE which forces a press-enter prompt when using vimdiff (even without your messages)

This was just to make sure my config doesn't affect the reproduction. I also tried `--clean` when I saw it recommended in the issue template.

The actual config doesn't have that option, and I get all the same problems.

If you want to play around with `jj`, here's what I was trying. `edit-args` is the important option.

```toml
[merge-tools.gvimdiff]
program = "gvim"
# `-d` enables diff mode. `-f` makes vim run in foreground even if it starts a GUI.
# The other options make sure that only the output file can be modified.
merge-args = ["-f", "-d", "$output", "-M", "$left", "$base", "$right",
              "-c", "wincmd J", "-c", "set modifiable", "-c", "set write",
              "-c", "/<<<<<</+2"]
merge-tool-edits-conflict-markers = true
# Directory diffing is barely usable in vimdiff without additional plugins
edit-args = [
    "-f", "-d", "$left", "$right", "-c", "echohl WarningMsg", "-c",
    # Or echomsg
    'echowin "Warning: using plain `vimdiff` as a diff editor is not recommended. See https://github.com/jj-vcs/jj/wiki/Vim for alternatives."',
    "-c", "echohl None",
]
diff-invocation-mode="file-by-file"
diff-args = ["-f", "-d", "$left", "$right"]
```

(Still haven't read your other suggestions, thank you for them!)
